server:
  port: 8080

spring:
  application:
    name: demo-provider
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: version=1.0,author=luyanjun
        healthCheckPath: /hello
        healthCheckInterval: 5s
        instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
        #instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

com:
  lu:
    key1: application
    properties:
      location: classpath